### ISSUE TITLE
TypeError: Cannot read property 'length' of null

### ISSUE THREAD

**Issue by Arcanemagus** [steelbrain/consistent-path#4]
Got this stack trace from [a report](https://github.com/AtomLinter/linter-php/issues/131) filed by @rickgregory over on `linter-php`: 

``` text
TypeError: Cannot read property 'length' of null
    at SyncWriteStream.write (fs.js:1981:38)
    at Object.execFileSync (child_process.js:471:20)
    at pathFromShellSync (/Users/rickg/.atom/packages/linter-php/node_modules/atom-linter/node_modules/consistent-path/node_modules/shell-path/index.js:52:28)
    at Function.module.exports.sync (/Users/rickg/.atom/packages/linter-php/node_modules/atom-linter/node_modules/consistent-path/node_modules/shell-path/index.js:34:11)
    at findOutPath (/Users/rickg/.atom/packages/linter-php/node_modules/atom-linter/node_modules/consistent-path/lib/index.js:27:62)
    at getPath (/Users/rickg/.atom/packages/linter-php/node_modules/atom-linter/node_modules/consistent-path/lib/index.js:17:16)
    at _exec (/Users/rickg/.atom/packages/linter-php/node_modules/atom-linter/lib/helpers.js:61:59)
    at Object.exec (/Users/rickg/.atom/packages/linter-php/node_modules/atom-linter/lib/helpers.js:152:10)
```

Is this a bug here, or somewhere deeper?

**Comment by steelbrain** [comment]
Opened here https://github.com/sindresorhus/shell-path/issues/10
